sudo: required

language: node_js
 
node_js:
  - 8.6.0

env:
  global:
    - CC_TEST_REPORTER_ID=f9a7cc51d41f847d9b5c91f469606222755355ec9ea001c6bd7a16d20f45941f
  matrix:
    - TASK="yarn run test"
    - TASK="npx cypress run"

before_script:
  - npm install
  - npm install coveralls

script:
  - $TASK

after_script:
  - "./node_modules/coveralls/bin/coveralls.js < ./test/unit/coverage/lcov.info"
  - docker-compose down --remove-orphans
