version: '3'
services:
  
  front:
    container_name: falko-front
    image: alaxalves/front:1.5
    command: ["./scripts/sh/start-dev.sh"]
    volumes:
      - .:/Falko-2017.2-FrontEnd
    external_links:
      - falko-backend
    ports:
      - 8080:8080
    networks:
      - falko-backend
      - default
    ipc: host

networks:
  falko-backend:
    external: true